# Generated by Django 5.2.3 on 2025-06-15 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='category',
            field=models.CharField(choices=[('wedding', 'Wedding'), ('portrait', 'Portrait'), ('event', 'Event')], default='wedding', max_length=20),
        ),
    ]
