# Generated by Django 5.2.3 on 2025-06-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_photo_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='portfolio_photos/'),
        ),
    ]
