# Generated by Django 5.2.3 on 2025-06-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='portfolio_photos/'),
        ),
    ]
