# Generated by Django 5.2.3 on 2025-06-26 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0006_alter_photo_image_alter_video_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='image',
            new_name='src',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='video',
            new_name='src',
        ),
    ]
