# Generated by Django 5.2.3 on 2025-06-26 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0007_rename_image_photo_src_rename_video_video_src'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='src',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='src',
            new_name='video',
        ),
    ]
